import * as React from 'react';
import { useNavigate } from 'react-router-dom';
import { CopyButton, Icon, useToast } from '@laplace-one/ui';
import { useClient, useSlot, useLaplaceContext } from '@laplace-one/sdk/react';
import {
  mapLaplaceError,
  toBaseUnits,
  slotToApproxTime,
  type Cluster,
} from '@laplace-one/sdk';
import { address } from '@solana/kit';
import { useValidityConfigs } from '../../indexer/hooks';
import { env } from '../../env';
import {
  initialCreate,
  validateStep1,
  validateStep2,
  computeExpirySlot,
  buildAsset,
  buildCriterion,
  hexToBytes,
  toBytes32Hex,
  type CreateState,
  type Recipe,
} from './createState';
import styles from './Create.module.css';

/** Small devnet SPL preset list (real mint + decimals). */
const SPL_PRESETS: Array<{ label: string; mint: string; decimals: number }> = [
  { label: 'USDC-Dev', mint: '4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU', decimals: 6 },
];

const RECIPES: Array<{ k: Recipe; icon: string; title: string; tier: 'official' | 'unverified'; blurb: string }> = [
  { k: 'hashlock', icon: 'eva:lock-outline', title: 'Hashlock', tier: 'official', blurb: 'Release on reveal of a SHA256 preimage. Ideal for atomic cross-chain swaps.' },
  { k: 'validity', icon: 'eva:shield-outline', title: 'Validity · SP1', tier: 'official', blurb: 'Release on a Groth16 validity proof bound to a registered ValidityConfig.' },
  { k: 'custom', icon: 'eva:cube-outline', title: 'Custom', tier: 'unverified', blurb: 'Escrow against any criterion program. Unverified by default — read the code.' },
];

function fmtTime(d: Date): string {
  return d.toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' });
}

export default function Create() {
  const nav = useNavigate();
  const slot = useSlot();
  const client = useClient();
  const { signer } = useLaplaceContext() as { signer?: { address: string } };
  const { toast } = useToast();
  const configs = useValidityConfigs();

  const [step, setStep] = React.useState<1 | 2 | 3>(1);
  const [s, setS] = React.useState<CreateState>(initialCreate);
  const [busy, setBusy] = React.useState(false);
  const set = <K extends keyof CreateState>(k: K, v: CreateState[K]) => setS((p) => ({ ...p, [k]: v }));

  const step1 = validateStep1(s);
  const step2 = validateStep2(s);
  const expirySlot = computeExpirySlot(slot, s.expiryMinutes);
  const expiryTime = slot > 0n ? slotToApproxTime(expirySlot, slot) : null;

  const [pending, setPending] = React.useState<Uint8Array | undefined>(undefined);
  function genSecret() {
    const b = new Uint8Array(32);
    crypto.getRandomValues(b);
    // clear any prior save gate; hold the generated bytes pending the "I saved it" checkbox
    setS((p) => ({ ...p, secret: undefined }));
    setPending(b);
  }

  async function submit() {
    if (!signer) { toast('Connect your wallet first', 'error'); return; }
    setBusy(true);
    try {
      const res = await client.createIntent({
        maker: signer as never,
        receiver: address(s.receiver),
        refundRecipient: s.refund ? address(s.refund) : undefined,
        asset: buildAsset(s),
        amount: toBaseUnits(s.amount, s.decimals),
        expirySlot: computeExpirySlot(slot, s.expiryMinutes),
        criterion: buildCriterion(s),
      });
      toast(`Intent created · ${res.signature.slice(0, 8)}…`);
      nav('/app/intent/' + res.intentPda);
    } catch (e) {
      toast(mapLaplaceError(e).message, 'error');
    } finally {
      setBusy(false);
    }
  }

  return (
    <section className="wrap">
      <div className={styles.createWrap}>
        <div className={styles.head}>
          <div>
            <h1>Create intent</h1>
            <p>Escrow funds against a release criterion on {env.cluster}.</p>
          </div>
        </div>

        <StepsBar step={step} />

        {!signer && (
          <div className={styles.warnBox}>
            <Icon icon="eva:alert-triangle-outline" />
            <p>Connect a wallet to sign and fund the escrow. You can fill in the form first.</p>
          </div>
        )}

        {step === 1 && (
          <Step1
            s={s}
            set={set}
            expirySlot={expirySlot}
            expiryTime={expiryTime}
            presets={SPL_PRESETS}
          />
        )}

        {step === 2 && (
          <Step2
            s={s}
            set={set}
            configs={configs}
            pending={pending}
            genSecret={genSecret}
          />
        )}

        {step === 3 && (
          <Review s={s} cluster={env.cluster} expirySlot={expirySlot} expiryTime={expiryTime} />
        )}

        <div className={styles.createNav}>
          <button
            type="button"
            className={`${styles.actBtn} ${styles.neutral}`}
            disabled={step === 1 || busy}
            onClick={() => setStep((p) => (p > 1 ? ((p - 1) as 1 | 2 | 3) : p))}
          >
            Back
          </button>
          {step < 3 ? (
            <button
              type="button"
              className={styles.actBtn}
              disabled={(step === 1 && !step1.ok) || (step === 2 && !step2.ok)}
              title={step === 1 ? step1.reason : step2.reason}
              onClick={() => setStep((p) => ((p + 1) as 1 | 2 | 3))}
            >
              Next
            </button>
          ) : (
            <button
              type="button"
              className={styles.actBtn}
              disabled={!signer || !step1.ok || !step2.ok || busy}
              onClick={submit}
            >
              {busy ? 'Signing…' : signer ? 'Create intent' : 'Connect wallet'}
            </button>
          )}
        </div>
      </div>
    </section>
  );
}

function StepsBar({ step }: { step: 1 | 2 | 3 }) {
  const labels = ['Escrow & parties', 'Criterion recipe', 'Review & sign'];
  return (
    <div className={styles.stepsBar}>
      {labels.map((label, i) => {
        const n = (i + 1) as 1 | 2 | 3;
        const cls = `${styles.stepdot} ${n === step ? styles.active : ''} ${n < step ? styles.done : ''}`;
        return (
          <React.Fragment key={label}>
            <div className={cls}>
              <span className={styles.num}>{n < step ? '✓' : n}</span>
              <span className={styles.stxt}>{label}</span>
            </div>
            {i < labels.length - 1 && (
              <div className={`${styles.stepline} ${n < step ? styles.done : ''}`} />
            )}
          </React.Fragment>
        );
      })}
    </div>
  );
}

function Step1({
  s,
  set,
  expirySlot,
  expiryTime,
  presets,
}: {
  s: CreateState;
  set: <K extends keyof CreateState>(k: K, v: CreateState[K]) => void;
  expirySlot: bigint;
  expiryTime: Date | null;
  presets: Array<{ label: string; mint: string; decimals: number }>;
}) {
  return (
    <div>
      <div className={styles.field}>
        <label>Asset</label>
        <div className={styles.segAsset}>
          <button
            type="button"
            className={s.asset === 'sol' ? styles.active : undefined}
            onClick={() => { set('asset', 'sol'); set('decimals', 9); }}
          >
            SOL
          </button>
          <button
            type="button"
            className={s.asset === 'spl' ? styles.active : undefined}
            onClick={() => { set('asset', 'spl'); set('decimals', 6); }}
          >
            SPL token
          </button>
        </div>
      </div>

      {s.asset === 'spl' && (
        <>
          <div className={styles.field}>
            <label>Token preset</label>
            <select
              value={presets.find((p) => p.mint === s.mint)?.label ?? ''}
              onChange={(e) => {
                const p = presets.find((x) => x.label === e.target.value);
                if (p) { set('mint', p.mint); set('decimals', p.decimals); }
              }}
            >
              <option value="">Custom mint…</option>
              {presets.map((p) => (
                <option key={p.label} value={p.label}>{p.label} · {p.mint.slice(0, 4)}…{p.mint.slice(-4)}</option>
              ))}
            </select>
          </div>
          <div className={styles.field}>
            <label>Mint address</label>
            <input
              placeholder="token mint address"
              value={s.mint}
              onChange={(e) => set('mint', e.target.value.trim())}
            />
          </div>
          <div className={styles.field}>
            <label>Decimals</label>
            <input
              inputMode="numeric"
              value={String(s.decimals)}
              onChange={(e) => set('decimals', Number(e.target.value) || 0)}
            />
          </div>
        </>
      )}

      <div className={styles.field}>
        <label>Amount</label>
        <input
          inputMode="decimal"
          placeholder="0.0"
          value={s.amount}
          onChange={(e) => set('amount', e.target.value.trim())}
        />
      </div>

      <div className={styles.field}>
        <label>Receiver</label>
        <input
          placeholder="receiver address"
          value={s.receiver}
          onChange={(e) => set('receiver', e.target.value.trim())}
        />
      </div>

      <div className={styles.field}>
        <label>Refund recipient</label>
        <input
          placeholder="defaults to maker (you)"
          value={s.refund}
          onChange={(e) => set('refund', e.target.value.trim())}
        />
        <div className={styles.hint}>If unfulfilled after expiry, the escrow refunds here. Leave blank to use the maker.</div>
      </div>

      <div className={styles.field}>
        <label>Expiry (minutes from now)</label>
        <input
          inputMode="numeric"
          value={String(s.expiryMinutes)}
          onChange={(e) => set('expiryMinutes', Number(e.target.value) || 0)}
        />
        <div className={styles.hint}>
          Expiry slot {String(expirySlot)}
          {expiryTime ? ` · ≈ ${fmtTime(expiryTime)}` : ''}
        </div>
      </div>
    </div>
  );
}

function Step2({
  s,
  set,
  configs,
  pending,
  genSecret,
}: {
  s: CreateState;
  set: <K extends keyof CreateState>(k: K, v: CreateState[K]) => void;
  configs: Array<{ configHash: string; guestElfHash: string }>;
  pending: Uint8Array | undefined;
  genSecret: () => void;
}) {
  return (
    <div>
      <div className={styles.recipeGrid}>
        {RECIPES.map((r) => (
          <div
            key={r.k}
            className={`${styles.recipe} ${s.recipe === r.k ? styles.sel : ''}`}
            onClick={() => set('recipe', r.k)}
          >
            <div className={styles.recipeIco}><Icon icon={r.icon} /></div>
            <h3>
              {r.title}
              <span className={`${styles.rtier} ${r.tier === 'official' ? styles.official : styles.unverified}`}>{r.tier}</span>
            </h3>
            <p>{r.blurb}</p>
          </div>
        ))}
      </div>

      {s.recipe === 'hashlock' && (
        <>
          <div className={styles.submode}>
            <button
              type="button"
              className={s.hashMode === 'generate' ? styles.active : undefined}
              onClick={() => set('hashMode', 'generate')}
            >
              Generate a secret
            </button>
            <button
              type="button"
              className={s.hashMode === 'paste' ? styles.active : undefined}
              onClick={() => set('hashMode', 'paste')}
            >
              I already have a hashlock
            </button>
          </div>

          {s.hashMode === 'generate' ? (
            <>
              <div className={styles.warnBox}>
                <Icon icon="eva:alert-triangle-outline" />
                <p>Save this secret now. Losing it means the intent can only be refunded; revealing it later is public and irreversible.</p>
              </div>
              {!pending ? (
                <button type="button" className={styles.actBtn} onClick={genSecret}>Generate secret</button>
              ) : (
                <>
                  <div className={styles.field}>
                    <label>Generated secret (32 bytes)</label>
                    <div className={styles.secretBox}>{toBytes32Hex(pending)}</div>
                    <CopyButton value={toBytes32Hex(pending)} className={`${styles.actBtn} ${styles.neutral}`} />
                  </div>
                  <label className={styles.hint} style={{ display: 'flex', alignItems: 'center', gap: 8, cursor: 'pointer' }}>
                    <input
                      type="checkbox"
                      style={{ width: 'auto', height: 'auto' }}
                      checked={!!s.secret}
                      onChange={(e) => set('secret', e.target.checked ? pending : undefined)}
                    />
                    I saved my secret — release the gate to continue.
                  </label>
                </>
              )}
            </>
          ) : (
            <div className={styles.field}>
              <label>criterion_data_hash (hashlock h)</label>
              <input
                placeholder="64 hex chars — counterparty hashlock"
                value={s.pastedHash}
                onChange={(e) => set('pastedHash', e.target.value.trim().replace(/^0x/i, ''))}
              />
              <div className={styles.hint}>Paste a counterparty's hashlock — e.g. the shared h for a cross-chain swap. No secret is stored locally.</div>
            </div>
          )}
        </>
      )}

      {s.recipe === 'validity' && (
        <ValiditySection
          value={s.configHash}
          onChange={(v) => set('configHash', v)}
          configs={configs}
        />
      )}

      {s.recipe === 'custom' && (
        <>
          <div className={styles.warnBox}>
            <Icon icon="eva:alert-triangle-outline" />
            <p><strong>Unverified by default.</strong> The protocol will escrow against any program you name — if its code is malicious or buggy, your deposit can be released to the wrong party. Read the deployed bytecode before proceeding.</p>
          </div>
          <div className={styles.field}>
            <label>Criterion program ID</label>
            <input
              placeholder="program address"
              value={s.customPid}
              onChange={(e) => set('customPid', e.target.value.trim())}
            />
          </div>
          <div className={styles.field}>
            <label>criterion_data_hash (hex)</label>
            <input
              placeholder="64 hex chars"
              value={s.customHash}
              onChange={(e) => set('customHash', e.target.value.trim().replace(/^0x/i, ''))}
            />
          </div>
          <div className={styles.field}>
            <label>Type the program ID again to acknowledge the risk</label>
            <input
              placeholder="re-type the program ID"
              value={s.customAck}
              onChange={(e) => set('customAck', e.target.value.trim())}
            />
            <div className={styles.hint}>
              {s.customPid.length > 0 && s.customPid === s.customAck ? (
                <span className={styles.ackOk}>
                  <Icon icon="eva:checkmark-circle-2" /> Acknowledged — you accept the risk of an unverified criterion.
                </span>
              ) : (
                'You are escrowing against unaudited code. Re-type the program ID exactly to confirm you understand.'
              )}
            </div>
          </div>
        </>
      )}
    </div>
  );
}

/** Validity criterion: pick a registered ValidityConfig, paste a hash, or register a new one. */
function ValiditySection({
  value,
  onChange,
  configs,
}: {
  value: string;
  onChange: (v: string) => void;
  configs: Array<{ configHash: string; guestElfHash: string }>;
}) {
  const client = useClient();
  const { signer } = useLaplaceContext() as { signer?: { address: string } };
  const { toast } = useToast();
  const [open, setOpen] = React.useState(false);
  const [elf, setElf] = React.useState('');
  const [vkey, setVkey] = React.useState('');
  const [fpi, setFpi] = React.useState('');
  const [busy, setBusy] = React.useState(false);
  // Optimistically surface a just-registered config: the indexer's cron can lag a couple of minutes
  // behind the ValidityConfigCreated event, so we add it locally so it's selectable immediately.
  const [extra, setExtra] = React.useState<Array<{ configHash: string; guestElfHash: string }>>([]);

  const all = [...configs, ...extra.filter((e) => !configs.some((c) => c.configHash === e.configHash))];
  const is64hex = (v: string) => /^[0-9a-fA-F]{64}$/.test(v);
  const isHexEven = (v: string) => v === '' || (/^[0-9a-fA-F]*$/.test(v) && v.length % 2 === 0);
  const canRegister = is64hex(elf) && is64hex(vkey) && isHexEven(fpi);

  async function register() {
    if (!signer) { toast('Connect your wallet first', 'error'); return; }
    setBusy(true);
    try {
      const res = await client.createValidityConfig(
        {
          guestElfHash: hexToBytes(elf),
          sp1VkeyHash: hexToBytes(vkey),
          fixedPublicInputs: hexToBytes(fpi),
        },
        { payer: signer as never },
      );
      const hash = toBytes32Hex(res.configHash);
      setExtra((p) => [{ configHash: hash, guestElfHash: elf }, ...p]);
      onChange(hash);
      toast(`ValidityConfig registered · ${hash.slice(0, 8)}…`);
      setOpen(false);
      setElf(''); setVkey(''); setFpi('');
    } catch (e) {
      toast(mapLaplaceError(e).message, 'error');
    } finally {
      setBusy(false);
    }
  }

  return (
    <div>
      <div className={styles.field}>
        <label>ValidityConfig</label>
        <select value={value} onChange={(e) => onChange(e.target.value)}>
          <option value="">Select a config hash…</option>
          {all.map((c) => (
            <option key={c.configHash} value={c.configHash}>
              {c.configHash.slice(0, 8)}… · elf {c.guestElfHash.slice(0, 6)}…
            </option>
          ))}
        </select>
        <input
          style={{ marginTop: 8 }}
          placeholder="…or paste a 64-hex config hash"
          value={value}
          onChange={(e) => onChange(e.target.value.trim().replace(/^0x/i, ''))}
        />
        <div className={styles.hint}>
          {all.length === 0
            ? `No ValidityConfigs registered on ${env.cluster} yet — register one below, or paste a hash.`
            : "The intent's criterion_data_hash = the config's config_hash. Fulfillment requires a Groth16 proof + public-input suffix, generated off-app."}
        </div>
      </div>

      <button type="button" className={styles.disclosure} onClick={() => setOpen((o) => !o)}>
        <Icon icon={open ? 'eva:minus-square-outline' : 'eva:plus-square-outline'} />
        Register a ValidityConfig
      </button>

      {open && (
        <div className={styles.registerBox}>
          <div className={styles.field}>
            <label>guest_elf_hash (32-byte hex)</label>
            <input placeholder="64 hex chars" value={elf} onChange={(e) => setElf(e.target.value.trim().replace(/^0x/i, ''))} />
          </div>
          <div className={styles.field}>
            <label>sp1_vkey_hash (32-byte hex)</label>
            <input placeholder="64 hex chars" value={vkey} onChange={(e) => setVkey(e.target.value.trim().replace(/^0x/i, ''))} />
          </div>
          <div className={styles.field}>
            <label>fixed_public_inputs (hex · optional)</label>
            <input placeholder="bytes bound into every proof — leave blank for none" value={fpi} onChange={(e) => setFpi(e.target.value.trim().replace(/^0x/i, ''))} />
            <div className={styles.hint}>config_hash = SHA256(domain ‖ spec ‖ elf ‖ vkey ‖ len ‖ fixed). Registering submits a transaction that publishes the config on-chain, then selects it above.</div>
          </div>
          <button type="button" className={styles.actBtn} disabled={busy || !signer || !canRegister} onClick={register}>
            {busy ? 'Registering…' : signer ? 'Register config' : 'Connect wallet'}
          </button>
        </div>
      )}
    </div>
  );
}

function Review({
  s,
  cluster,
  expirySlot,
  expiryTime,
}: {
  s: CreateState;
  cluster: Cluster;
  expirySlot: bigint;
  expiryTime: Date | null;
}) {
  const crit =
    s.recipe === 'hashlock'
      ? 'Hashlock · official'
      : s.recipe === 'validity'
        ? 'Validity · SP1 · official'
        : 'Custom · unverified';
  const commit: [string, string] =
    s.recipe === 'custom'
      ? ['Program ID', s.customPid || '—']
      : s.recipe === 'validity'
        ? ['Config hash', s.configHash ? '0x' + s.configHash : '—']
        : ['Hashlock', s.hashMode === 'generate' && s.secret ? 'derived from saved secret' : s.pastedHash ? '0x' + s.pastedHash : '—'];

  const rows: Array<[string, string]> = [
    ['Asset', s.asset === 'sol' ? 'SOL' : `SPL · ${s.mint.slice(0, 4)}…${s.mint.slice(-4)}`],
    ['Amount', `${s.amount || '0'} ${s.asset === 'sol' ? 'SOL' : `(×10^${s.decimals})`}`],
    ['Receiver', s.receiver || '—'],
    ['Refund recipient', s.refund || 'maker (you)'],
    ['Expiry', `+${s.expiryMinutes} min · slot ${String(expirySlot)}${expiryTime ? ` · ≈ ${fmtTime(expiryTime)}` : ''}`],
    ['Criterion', crit],
    commit,
    ['Cluster', cluster],
  ];

  return (
    <dl className={styles.reviewTable}>
      {rows.map(([k, v]) => (
        <div key={k} className={styles.reviewRow}>
          <dt>{k}</dt>
          <dd>{v}</dd>
        </div>
      ))}
    </dl>
  );
}
